const aOpts=(a,w)=>{let r=[a,...w].map(String).filter((x,i,z)=>z.indexOf(x)===i);for(const f of ['Birlikte çözüm ararım.','Nazik ve saygılı davranırım.','Sorumluluğumu zamanında yaparım.','Güvenilir bir yetişkinden yardım isterim.'])if(r.length<4&&!r.includes(f))r.push(f);return r.slice(0,4)},aQ=(p,v,a,w)=>[p,v,a,aOpts(a,w)];
const familyCases=['Bir aile üyesi üzgün görünüyor','Evde yapılacak işler birikti','Ailece yemek hazırlanıyor','Bir aile üyesi hastalandı','Kardeşler oyuncak konusunda anlaşamadı','Aile büyüklerinden biri anılarını anlatıyor','Ailece bir gezi planlanıyor','Bir aile üyesinin yardıma ihtiyacı var','Evde ortak bir karar alınacak','Bir aile üyesi başarı kazandı','Kardeşin ödevinde zorlanıyor','Aile albümüne bakılıyor','Ailece önemli bir gün kutlanıyor','Bir yanlış anlaşılma yaşandı','Evde herkes yorgun','Bir aile üyesi kendini yalnız hissediyor','Ailede farklı fikirler ortaya çıktı','Bir eşya yanlışlıkla kırıldı','Ailecek oyun oynanacak','Bir aile üyesi konuşmak istiyor','Evde yeni bir sorumluluk paylaşılacak','Bir aile büyüğü ziyarete geldi','Kardeşin senden özür diledi','Ailece geçmiş hakkında konuşuluyor','Bir aile üyesi korktuğunu söyledi'];
const family=Array.from({length:100},(_,i)=>{let s=familyCases[i%25],k=Math.floor(i/25);if(k===0)return aQ(s+'. Aile bağlarını güçlendiren davranış hangisidir?','💞 Sevgi ve dayanışma','Birbirimizi dikkatle dinleyip desteklemek',['Sorunu görmezden gelmek','Kaba konuşmak','Birbirimizi suçlamak']);if(k===1)return aQ(s+'. Aile içinde dayanışma nasıl gösterilebilir?','🤝 Birlikte daha güçlüyüz','Herkesin yaşına ve gücüne uygun katkı sağlamasıyla',['Bütün işi bir kişiye bırakarak','Kimseye yardım etmeyerek','Görevleri sürekli erteleyerek']);if(k===2)return aQ(s+'. Sevgi ve saygıya uygun iletişim hangisidir?','💬 Aile iletişimi','Duygu ve düşünceleri sakin ve açık biçimde paylaşmak',['Söz kesmek','Bağırarak konuşmak','Küsmek']);return aQ(s+'. Bu durum ailenin önemini nasıl gösterir?','🏡 Ailemin önemi','Aile üyelerinin birbirine güven ve destek vermesiyle',['Ailede kimsenin sorumluluğu olmamasıyla','Sorunların saklanmasıyla','Yalnızca hediye alınmasıyla'])});
const mannersCases=['Birinden yardım istiyorsun','Birisi sana yardım etti','Yanlışlıkla arkadaşına çarptın','Sınıfa girdin','Toplu taşımada yaşlı biri ayakta','Kütüphanede kitap okuyorsun','Sırada bekliyorsun','Misafirliğe gittin','Yemek masasına oturdun','Telefonla konuşan biri var','Bir arkadaşın konuşuyor','Toplantı yapılan bir ortama girdin','Bir eşya ödünç almak istiyorsun','Aldığın eşyayı geri veriyorsun','Birisi sana teşekkür etti','Kalabalık bir kapıdan geçeceksin','Sinema salonundasın','Parkta çöp oluştu','Komşunla karşılaştın','Bir arkadaşın farklı düşünüyor','Hapşırdın','Birinin özel eşyasını gördün','Oyun sırasında sıra sana gelmedi','Bir yetişkin konuşurken söz almak istiyorsun','Bir arkadaşına öneride bulunacaksın'];
const manners=Array.from({length:100},(_,i)=>{let s=mannersCases[i%25],k=Math.floor(i/25);if(k===0)return aQ(s+'. Kullanılması gereken en uygun nezaket ifadesi veya davranışı hangisidir?','🌸 Nezaket','Duruma uygun nazik bir ifade kullanmak',['Emir vererek konuşmak','Kaba söz söylemek','Karşıdakini görmezden gelmek']);if(k===1)return aQ(s+'. Başkalarının haklarına saygı göstermek için ne yapmalısın?','⚖️ Haklara saygı','Sıraya ve ortak kurallara uymalıyım.',['Kendime ayrıcalık istemeliyim.','Başkalarının sırasını almalıyım.','Kuralları yok saymalıyım.']);if(k===2)return aQ(s+'. Bulunulan ortamın görgü kuralına uygun davranış hangisidir?','🏙️ Görgü kuralları','Ortamı ve çevremdeki kişileri rahatsız etmeyecek biçimde davranmak',['Yüksek sesle konuşmak','Ortak alanı kirletmek','İzinsiz eşya almak']);return aQ(s+'. Bir hata veya rahatsızlık oluştuğunda ne yapılmalıdır?','🙏 Nezaket sözcükleri','Özür dileyip davranışı düzeltmek',['Hatayı başkasına yüklemek','Gülüp uzaklaşmak','Aynı davranışı sürdürmek'])});
const duties=['Odanı düzenlemek','Oyuncaklarını toplamak','Sofranın hazırlanmasına yardım etmek','Okul çantanı hazırlamak','Ödevini zamanında yapmak','Dişlerini fırçalamak','Kirli kıyafetini sepete koymak','Evcil hayvanın suyunu kontrol etmek','Kitaplarını yerine koymak','Bitkileri sulamak','Kullanılan tabağı mutfağa götürmek','Çöpleri uygun kutuya atmak','Kişisel eşyalarını korumak','Okul kurallarına uymak','Verilen grup görevini yapmak','Yatağını düzeltmek','İsraf etmeden su kullanmak','Işıkları gereksiz yere açık bırakmamak','Kardeşine yaşına uygun yardım etmek','Ortak alanı temiz bırakmak','Ders araçlarını korumak','Zamanında hazırlanmak','Aile içi kararlara katılmak','Söz verdiğin işi tamamlamak','Yapamadığın görev için yardım istemek'];
const responsibility=Array.from({length:100},(_,i)=>{let s=duties[i%25],k=Math.floor(i/25);if(k===0)return aQ('“'+s+'” görevi sana verildi. Sorumlu davranış hangisidir?','✅ Görevimi yapıyorum','Görevi zamanında ve özenle tamamlamak',['Görevi başkasına bırakmak','Görevi unutmuş gibi yapmak','Sürekli ertelemek']);if(k===1)return aQ('“'+s+'” sırasında zorlandın. Ne yapmalısın?','🆘 Çözüm arıyorum','Önce çaba gösterip gerekirse uygun kişiden yardım istemeliyim.',['Görevi tamamen bırakmalıyım.','Başkasını suçlamalıyım.','Eşyaları dağıtmalıyım.']);if(k===2)return aQ('“'+s+'” neden bir sorumluluktur?','🌱 Sorumluluk bilinci','Kendimize ve birlikte yaşadığımız kişilere katkı sağlar.',['Yalnızca ceza almamak içindir.','Hiç kimseyi etkilemez.','İstediğimiz zaman yok sayılabilir.']);return aQ('“'+s+'” tamamlandıktan sonra en uygun davranış hangisidir?','🔎 Görev kontrolü','Görevin doğru tamamlandığını kontrol etmek',['Yapılan işi bozmak','Aynı işi gereksiz yere tekrarlamak','Diğer kişilerin görevlerine karışmak'])});
const sections=[
{code:'HB.2.3.1',color:'#d5577d',soft:'#ffeaf1',icon:'💞',title:'Ailemin Önemi',intro:'Sevgi, saygı, güven, iletişim ve dayanışmanın aile bağlarına katkısını değerlendir.',badge:'Aile Bağları Rozeti',games:[{id:'aile100',icon:'🏡',title:'Aile Bağları Macerası',desc:'100 farklı aile durumunda yapıcı davranışı seç.',q:family}]},
{code:'HB.2.3.2',color:'#7255c8',soft:'#f1edff',icon:'🌸',title:'Nezaket ve Görgü Kuralları',intro:'Evde, okulda ve toplumsal alanlarda uygun nezaket davranışlarını uygula.',badge:'Nezaket Elçisi Rozeti',games:[{id:'nezaket100',icon:'🙏',title:'Nezaket Şehri',desc:'100 farklı durumda nazik ve saygılı seçimi yap.',q:manners}]},
{code:'HB.2.3.3',color:'#278b70',soft:'#e8faf4',icon:'✅',title:'Görev ve Sorumluluklarım',intro:'Yaşına uygun görevleri üstlen, zamanında tamamla ve gerektiğinde yardım iste.',badge:'Sorumluluk Rozeti',games:[{id:'gorev100',icon:'📋',title:'Sorumluluk Kahramanı',desc:'100 görev durumunda doğru sorumluluk davranışını seç.',q:responsibility}]}
];
let state=JSON.parse(localStorage.getItem("ailem-toplum-progress")||'{"score":0,"wins":{}}');
const worlds=document.getElementById("worlds"),modal=document.getElementById("modal");
let game=null,qi=0,correct=0,locked=false;

function render(){
 worlds.innerHTML=sections.map((s,si)=>`<article class="world" style="--c:${s.color};--soft:${s.soft}">
 <div class="world-head"><div class="world-icon">${s.icon}</div><div><div class="code">${s.code}</div><h2>${si+1}. Bölüm · ${s.title}</h2><div>${s.badge} ${sectionWon(s)?"✅":"🔒"}</div></div></div>
 <div class="intro"><b>Konuyu keşfet</b>${s.intro}</div>
 <div class="cards">${s.games.map(g=>`<button class="card" data-id="${g.id}" style="--c:${s.color}"><span class="emoji">${g.icon}</span><h3>${g.title}</h3><p>${g.desc}</p><strong>${state.wins[g.id]?"Tamamlandı ✓":"Oyunu aç →"}</strong></button>`).join("")}</div></article>`).join("");
 document.querySelectorAll(".card").forEach(b=>b.onclick=()=>start(findGame(b.dataset.id)));
 updateProgress();
}
function findGame(id){for(const s of sections){const g=s.games.find(x=>x.id===id);if(g)return {...g,section:s}}}
function sectionWon(s){return s.games.every(g=>state.wins[g.id])}
function updateProgress(){document.getElementById("stars").textContent=state.score;document.getElementById("badges").textContent=sections.filter(sectionWon).length+"/3"}
function start(g){game={...g,q:[...g.q].sort(()=>Math.random()-.5)};qi=0;correct=0;locked=false;modal.hidden=false;document.body.style.overflow="hidden";showQ()}
function showQ(){
 const q=game.q[qi];locked=false;
 document.getElementById("gameHead").innerHTML=`<div class="game-title">${game.icon} ${game.title}</div><div class="game-meta">${game.section.code} · ${correct*10} puan</div>`;
 document.getElementById("bar").style.width=(qi/game.q.length*100)+"%";
 document.getElementById("question").innerHTML=`<div class="qno">GÖREV ${qi+1} / ${game.q.length}</div><div class="prompt">${q[0]}</div><div class="scene">${q[1]}</div>`;
 const opts=[...q[3]].sort(()=>Math.random()-.5);
 document.getElementById("answers").innerHTML=opts.map(a=>`<button class="answer">${a}</button>`).join("");
 document.getElementById("feedback").textContent="";document.getElementById("next").hidden=true;
 document.querySelectorAll(".answer").forEach(b=>b.onclick=()=>answer(b,q[2]));
}
function answer(btn,right){if(locked)return;locked=true;document.querySelectorAll(".answer").forEach(b=>{b.disabled=true;if(b.textContent===String(right))b.classList.add("good")});if(btn.textContent===String(right)){correct++;btn.classList.add("good");document.getElementById("feedback").textContent="Harika! Doğru cevap. +10 puan ⭐"}else{btn.classList.add("bad");document.getElementById("feedback").textContent="Birlikte öğrendik! Doğru cevap: "+right}document.getElementById("next").hidden=false}
document.getElementById("next").onclick=()=>{qi++;if(qi<game.q.length)showQ();else finish()};
function finish(){const won=correct>=80;if(won&&!state.wins[game.id]){state.wins[game.id]=true;state.score+=correct*10}else if(!state.wins[game.id])state.score+=correct*10;localStorage.setItem("ailem-toplum-progress",JSON.stringify(state));document.getElementById("bar").style.width="100%";document.getElementById("question").innerHTML=`<div class="result"><div class="cup">${won?"🏆":"🌱"}</div><h2>${won?"Görev tamamlandı!":"Bir kez daha deneyelim!"}</h2><p>100 sorudan ${correct} tanesini doğru cevapladın. ${won?"Bu oyunun yıldızını kazandın!":"80 doğruya ulaştığında oyunu tamamlayacaksın."}</p><button class="play-again" id="again">${won?"Oyunlara dön":"Yeniden oyna"}</button></div>`;document.getElementById("answers").innerHTML="";document.getElementById("feedback").textContent="";document.getElementById("next").hidden=true;document.getElementById("again").onclick=()=>won?closeGame():start(game);render()}
function closeGame(){modal.hidden=true;document.body.style.overflow="";render()}
document.getElementById("close").onclick=closeGame;modal.onclick=e=>{if(e.target===modal)closeGame()};
document.getElementById("reset").onclick=()=>{if(confirm("Tüm puan ve rozetler sıfırlansın mı?")){state={score:0,wins:{}};localStorage.setItem("ailem-toplum-progress",JSON.stringify(state));render()}};
render();